### ISSUE TITLE
Can we provide a choice for native Tor and VPN support (from the landingpage)

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#15]
Can we run this on the RPi?
Can we run this on the router?
Can we integrate the NetAidKit?
Can we fork the NetAidKit integration?

**Comment by nllz** [comment]
Using Tor from the router makes no sense, this would only make sense for censorship circumvention.

**Comment by Beltrandroid** [comment]
VPN is still worth it to use.
Can we setup direct access through VPN without option of non-VPN from the landing page?
There is some scenario for this target group on which non-vpn is needed?

**Comment by nllz** [comment]
The biggest threat for the users is on site surveillance, a VPN or Tor connection will by no means increase security for the user for that, and is more likely to create a false sense of security. 

But we'll implement VPN on the router, but will not mention it and push users to install Tor and/or a VPN at their endpoint devices.
