### ISSUE TITLE
Make a decision (tree) to find out which setup is the best

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#17]
Four different setups:
1.
4g USB modem/dongle + RPi + antenna
(in which RPi functions as router)
(cheapest but depends on most config of RPi)

2.
4g dongle + router TPLink + RPi 
(in which RPi functions for extra services)  
(a bit more expensive but with less config and dedicated hardware (RPi doesn't do networking)

3.
4g router&modem DLink + RPi
(in which RPi functions for extra services)
(most expensive but with integrated dongle, modem and router (RPi doesn't do networking)
# assumption is that this is pretty much a ready-made solution
1. 
   4g dongle + netaidkit + RPi

Which device setup (mentioned above) is most efficient?
Which device setup (mentioned above) is most resilient?
Which device setup (mentioned above) is easiest reproducible?
Which device setup (mentioned above) is most functional?

**Comment by nllz** [comment]
Option 1 (RPi + 3G/4G dongle + WiFi Antenna) is most efficient because RPi has sufficient computing power, the setup is the easiest and it's most configurable.
