### ISSUE TITLE
Brainstorm/Research/Document useful local services for the device

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#18]
Maps
Legislation
Guides
Resources
Forums
Chat services
Libraries
Message board
etc
Please include link and the reason why it should be offline and not online.

**Comment by Beltrandroid** [comment]
Location service to know in real time where the protest is so people that joins it after it has started can find it. And also real time feed of practical things that are needed, like food, raincoats, water...

**Comment by Beltrandroid** [comment]
Radio streaming

Hosted in the remote server, must have implementation to stream locally from the hotspot.
http://icecast.org/

**Comment by nllz** [comment]
Have the different software packages and use cases been documented for this?

**Comment by nllz** [comment]
Pls provide links, descriptions, user stories and features if we want to implement this.
