### ISSUE TITLE
Design of Landingpage

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#19]
Presenting the hotspot as refugee hotspot, link to VPN, Tor, local services, local documentation, documentation of the collective.
-Decision on how to facilitate SSMM sharing while preserving privacy of the users. (No FB tracking)

**Comment by Beltrandroid** [comment]
Embedding poems made by the collectives as welcoming to the Landing Page

http://heretosupport.nl/blog_post/poetic-performances-in-felix-meritis-2/

**Comment by postdigital** [comment]
![refugeehotspot](https://cloud.githubusercontent.com/assets/436937/12851122/7cda1d1e-cc28-11e5-9196-9ea9d013f902.jpg)
First version of the landing page is done!

**Comment by postdigital** [comment]
![refugeehotspot](https://cloud.githubusercontent.com/assets/436937/12850490/3e4d1c7a-cc25-11e5-9693-06822c7e3e01.jpg)

**Comment by postdigital** [comment]
[refugeehotspot.zip](https://github.com/RefugeeHotspot/RefugeeHotspot/files/119393/refugeehotspot.zip)
SVG file

**Comment by postdigital** [comment]
[refugeehotspot.zip](https://github.com/RefugeeHotspot/RefugeeHotspot/files/119397/refugeehotspot.zip)
SVG file.

**Comment by postdigital** [comment]
![refugeehotspot_mobile](https://cloud.githubusercontent.com/assets/436937/12851791/1167f5d4-cc2c-11e5-9389-73d7fffec71d.jpg)
Mobile version

**Comment by Beltrandroid** [comment]
v0.1 Done!
