### ISSUE TITLE
Get NetaidKit working with 4G Dongle + SIM

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#20]
Anyone that wants to develop on the NetAidKit source during the hackathon, word of advice: make sure you have your OpenWRT build environment up and running before the hackathon, it takes ages to install and is ~ 3 GB in size(!)

**Comment by nllz** [comment]
Working, but not documented, might be useful for later. Mensoh, could you dump the fixes for this somewhere?

**Comment by Beltrandroid** [comment]
Great, it will be useful to have this even if finally we go for the Rpi setup.
