### ISSUE TITLE
Web Radio broadcasting service from the device

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#24]
Online radio service directly through the hotspot

**Comment by postdigital** [comment]
Is this service still considered by the SERVICE group?

**Comment by nllz** [comment]
This could be done by running a audio streaming server (like Icecast http://icecast.org/) on the Raspberry Pi. Question is: where does the audio come from (source), and where does it stream to. Will people listen locally, or do you want to upload to the net? If the latter is the case, maybe we want to run the server somewhere else.

**Comment by Beltrandroid** [comment]
This is in replacement of the analog radio station that was in the proposal before. Instead we can have an internet based radio service.
It can run in the server together with the rest of remote services. It would have an easy way to record locally, ould be as simple as clicking a red "Rec" button from the landing page, and might be a good small example to demonstrate the device and remote services in action at the end of the hackathon.

**Comment by nllz** [comment]
The use case for this is not totally clear to me. Would it not be better to do all this on endpoint devices and on a remote server? What would be hosted on the Refugee Hotspot?
