### ISSUE TITLE
(how to) creative ways to perform/carry/use the device in demonstrations

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#25]
Using it as an umbrella?
As a roman empire-like mast?
Can the device next to providing an internet connection become a tool for sousveillance? (Creating a protected space by filming and live-streaming all actions around the protest : especially police / media) 
How to visualize and give presence to the users interacting with the device?
How to find forms of engaging and making visible in the protest the users that are connected online?
How to create meaningful, joyful and engaging interactions between the physical and virtual users?

**Comment by postdigital** [comment]
Too specific/too related to the framework of protests. It is decided in communication between SERVICES and IMPLEMENTATION group to not focus on protests specifically. (When people are protesting they are already together... The point is rather to facilitate communication and activate people in permanent situation of living together on location.)
