### ISSUE TITLE
Integrate SSMM sharing buttons into the landing page

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#26]
How to add the FB and Twitter buttons on the landing page of the device so we can easily share items to SSMM:
Do we need a FB account created with the post in order to share it?

**Comment by nllz** [comment]
Would this not be problematic vis a vis privacy etc? Am not sure if it would be a good idea to promote usage of facebook because of sensitivity of the target group.

**Comment by Beltrandroid** [comment]
I understand the point but most of the collectives use FB as their main media platform for communicating protests, actions, evictions, ask for support, etc.

**Comment by nllz** [comment]
Am really quite concerned about the network mapping & surveillance effect. This mean that all traffic from the landingpage (which is everything) can be tracked by the Facebook plugin. 

This would also make it difficult to use as FLOSS project.

**Comment by nllz** [comment]
Am really quite concerned about the network mapping & surveillance effect. This mean that all traffic from the landingpage (which is everything) can be tracked by the Facebook plugin. 

This would also make it difficult to use as FLOSS project.

**Comment by nllz** [comment]
Perhaps we should open a general ticket about the content / functioning of the landingpage? About messaging, functionality and policies?

**Comment by Beltrandroid** [comment]
We want to facilitate the sharing functionalities while at the same time preserving and protecting the privacy of the users. How to find a balance that allows the 2? Good point for a new ticket.

**Comment by nllz** [comment]
+1, discussion might be easier if we first establish what we want to achieve with the landingpage :)
New general ticket?

**Comment by Beltrandroid** [comment]
Added into #19 "Design of Landing Page"

"-Decision on how to facilitate SSMM sharing while preserving privacy of the users. (No FB tracking)"

**Comment by postdigital** [comment]
What exactly do we want to share on social media from the landing page?! Specific documents (propaganda materials?) or just make this project more popular, or... etc? Manuel, please can you make it more specific, also in relation to the landing page design we have so far?
