### ISSUE TITLE
Virtual flyering – Think about ways how to spread propaganda to passersby during the protest

### ISSUE THREAD

**Issue by jannaullrich** [RefugeeHotspot/RefugeeHotspot#28]
Material that could be spread through WiFi-hotspot :
– General information about the 'We Are Here' movement – poems by WAH members – snippets of the documentary about WAH – short stories ( Asylum procedure through the eyes of the refugees ) ... 

How could this material be spread to passersby during the protest? Downloading them from the landing page? And how to engage these passersby to share the material further?
(thinking of e-cards, memes, share-on-facebook, ...)

**Comment by postdigital** [comment]
Too specific/too related to the framework of protests. It is decided in communication between SERVICES and IMPLEMENTATION group to not focus on protests specifically. (When people are protesting they are already together... The point is rather to facilitate communication and activate people in permanent situation of living together on location.)
