### ISSUE TITLE
Developing location service to know in real time where the protest is so people that joins it after it has started can find it.

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#30]
And also real time feed of practical things that are needed, like food, raincoats, water...

**Comment by postdigital** [comment]
Too specific/too related to the framework of protests. It is decided in communication between SERVICES and IMPLEMENTATION group to not focus on protests specifically. (When people are protesting they are already together... The point is rather to facilitate communication and activate people in permanent situation of living together on location.)
