### ISSUE TITLE
Language (translation)

### ISSUE THREAD

**Issue by postdigital** [RefugeeHotspot/RefugeeHotspot#33]
It would be great to create different language versions of the landing page (English, Dutch, French, Arabic... etc). Anybody can arrange the translations?

**Comment by JBinsbergen** [comment]
I put out a request to translate in my network.

**Comment by JBinsbergen** [comment]
I have put out a request on two refugee/volunteering Fb groups. 7 and 5k members. 

## If nothing we can try to list this transition on a mechanical Turk platform. 

Joram Binsbergen

**Comment by Beltrandroid** [comment]
I'll take care of the Spanish, French, Arabic, and Catalan one.

**Comment by Beltrandroid** [comment]
Arabic translation done

**Comment by Beltrandroid** [comment]
Spanish translation done

**Comment by Beltrandroid** [comment]
French and dutch translations on their way

**Comment by Beltrandroid** [comment]
French added

**Comment by Beltrandroid** [comment]
Dutch added, Closing this for now!
