### ISSUE TITLE
Configure remote server for remote services

### ISSUE THREAD

**Issue by Beltrandroid** [RefugeeHotspot/RefugeeHotspot#35]
Remote server, hosting for now this basic services:

radio streaming #24 
wiki
non-google maps?
...

**Comment by DrWhax** [comment]
A mediawiki has been setup.

I need requirements for:
- radio streaming
- openstreetmap (provide me with actions that someone would have to take)

**Comment by DrWhax** [comment]
The wiki is a private one for the moment and you need an account to login and see content.

**Comment by Beltrandroid** [comment]
Requirements for Radio straming in #24 
Link to remote server?
Bring us a visit upstairs for more info!

**Comment by Beltrandroid** [comment]
@DrWhax ?

**Comment by nllz** [comment]
Is this a duplicate  of https://github.com/RefugeeHotspot/RefugeeHotspot/issues/24 ?
