### ISSUE TITLE
Make presentation for RIPE etc

### ISSUE THREAD

**Issue by nllz** [RefugeeHotspot/RefugeeHotspot#54]

**Comment by shane-kerr** [comment]
Niels put this together, and Shane presented this. 

Video is here:

https://ripe72.ripe.net/archives/video/113/

Slides are here:

https://ripe72.ripe.net/presentations/35-Refugee-Hotspot-Lightning-Talk-RIPE-72.pdf

**Comment by shane-kerr** [comment]
Niels put this together, and Shane presented this. 

Video is here:

https://ripe72.ripe.net/archives/video/113/

Slides are here:

https://ripe72.ripe.net/presentations/35-Refugee-Hotspot-Lightning-Talk-RIPE-72.pdf
