### ISSUE TITLE
Decide policies and implementation of QoS

### ISSUE THREAD

**Issue by nllz** [RefugeeHotspot/RefugeeHotspot#8]
Bandwith will be limited, how will it be divided among users? Will it be simply that all bandwidth gets shared with all users equally? Which part of software will take care of this?

**Comment by Beltrandroid** [comment]
I heard there was agreement in equally distributing speed limits per user. With a problem for video streaming (that I think is super necessary to have) How is the limit implemented?

**Comment by nllz** [comment]
The limit is implemented at 50 k/s per user, video streaming over 3G is not likely to function over the limited bandwidth we have on a 3G / 4G connection, especially if it's shared. .
